---
name: Build and Deploy to GKE
on:
  - push
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ env.GKE_CLUSTER }}
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: gke-test
  IMAGE: sudhadn/gha-demo:latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
      - run: gcloud --quiet auth configure-docker
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: us-central1-c
          credentials: ${{ secrets.GKE_SA_KEY }}
      - name: Deploy
        run: |-
          kubectl apply -f gke-deployment-service.yml
          kubectl get services -o wide
